services:
  server:
    build:
      context: .
      args:
        - VITE_API_SERVER=${VITE_API_SERVER}
    container_name: vatsim-flight-tracker
    env_file:
      - .env
    restart: always

  nginx-reverse-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/nginx/certs
    restart: always
    depends_on:
      - server
