services:
  server:
    build:
      context: .
      args:
        - VITE_API_SERVER=${VITE_API_SERVER}
    container_name: vatsim-flight-tracker
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always
