services:
  vatsim-flight-tracker:
    image: ghcr.io/beacon6/vatsim-flight-tracker:latest
    container_name: vatsim-flight-tracker
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    restart: always

  nginx-reverse-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/nginx/certs
    restart: always
    depends_on:
      - vatsim-flight-tracker

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/beacon/.docker/config.json:/config.json
    command:
      - "--cleanup"
      - "--interval"
      - "300"
