name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.3.1
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VATSIM_FLIGHT_TRACKER }}

  jobs:
    gcloud-deploy:
      runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_VATSIM_FLIGHT_TRACKER }}
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
      - name: Select gcloud project
        run: gcloud config set project vatsim-flight-tracker
      - name: Deploy to gcloud
        run: gcloud builds submit --tag gcr.io/vatsim-flight-tracker/express-server
