name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build --file Dockerfile --tag ghcr.io/vatsim-flight-tracker:latest \
        --build_arg VITE_API_SERVER=beacon6.com .

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: docker push ghcr.io/vatsim-flight-tracker:latest
