name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build \
          --tag ghcr.io/beacon6/vatsim-flight-tracker:latest \
          --tag ghcr.io/beacon6/vatsim-flight-tracker:${{ github.sha }} \
          --build-arg VITE_API_SERVER=beacon6.com .
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: docker push ghcr.io/beacon6/vatsim-flight-tracker --all-tags
